version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
handlers:
    clog:
        class: clog.CustomLogHandler
        level: INFO
        formatter: simple
        fname: audio_record.log
root:
    level: DEBUG
    handlers: [clog]
